apiVersion: v1
kind: Service
metadata:
  name: {{ include "softether.fullname" . }}
  labels:
    {{- include "softether.labels" . | nindent 4 }}
{{- if .Values.service.softether.annotations }}
  annotations:
    {{ toYaml .Values.service.softether.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.softether.type }}
{{- if .Values.service.softether.externalIPs }}
  externalIPs:
    {{ toYaml .Values.service.softether.externalIPs | nindent 4 }}
{{- end }}
  ports:
    - name: softether
      targetPort: softether
      port: {{ .Values.service.softether.port }}
      protocol: TCP
  selector:
    {{- include "softether.selectorLabels" . | nindent 4 }}