apiVersion: v1
kind: Service
metadata:
  name: {{ include "softether.fullname" . }}
  labels:
    {{- include "softether.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP:
    {{ toYaml .Values.service.loadBalancerIP | nindent 4 }}
{{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
    {{ toYaml .Values.service.externalIPs | nindent 4 }}
{{- end }}
  ports:
    - name: softether
      targetPort: softether
      port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "softether.selectorLabels" . | nindent 4 }}

---    
{{- if and .Values.service.l2tp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "softether.fullname" . }}-l2tp
  labels:
    {{- include "softether.labels" . | nindent 4 }}
{{- if .Values.service.l2tp.annotations }}
  annotations:
    {{ toYaml .Values.service.l2tp.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.l2tp.type }}
{{- if .Values.service.l2tp.loadBalancerIP }}
  loadBalancerIP:
    {{ toYaml .Values.service.l2tp.loadBalancerIP | nindent 4 }}
{{- end }}  
{{- if .Values.service.l2tp.externalIPs }}
  externalIPs:
    {{ toYaml .Values.service.l2tp.externalIPs | nindent 4 }}
{{- end }}
  ports:
    - name: ike
      targetPort: 500
      port: 500
      protocol: UDP
    - name: ipsec
      targetPort: 4500
      port: 4500
      protocol: UDP
  selector:
    {{- include "softether.selectorLabels" . | nindent 4 }}      
{{- end }}
