apiVersion: v1
kind: Service
metadata:
  name: {{ include "softether.fullname" . }}
  labels:
    {{- include "softether.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.externalIPs }}
  externalIPs:
    {{ toYaml .Values.service.externalIPs | nindent 4 }}
{{- end }}
  ports:
    - name: softether
      targetPort: softether
      port: {{ .Values.service.port }}
      protocol: TCP
    {{- if and .Values.service.l2tp.enabled }}
    - name: ike
      targetPort: ike
      port: 500
      protocol: UDP
    - name: ipsec
      targetPort: ipsec
      port: 4500
      protocol: UDP
    {{- end }}
  selector:
    {{- include "softether.selectorLabels" . | nindent 4 }}